# Generated by Django 3.1.2 on 2020-12-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_gameroommodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraphmodel',
            old_name='Paragraph',
            new_name='paragraph',
        ),
        migrations.AddField(
            model_name='paragraphmodel',
            name='title',
            field=models.CharField(default=models.CharField(max_length=240), max_length=30),
        ),
    ]
